config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'lists#index'
  resources :users, param: :slug, only: [:show, :new, :create, :update, :edit, :destroy] do
    member do
      get :following, :followers
    end
  end
  resources :lists, only: [ :index, :show, :create, :edit, :new, :update ] do
    resources :list_places, only: [:create, :destroy]
    resources :favourites
  end

  resources :places, only: [:show, :update, :edit, :destroy]

  #resources :listplaces, only: [:new, :create, :destroy]
  resources :favourites, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :relationships, only: [:create, :destroy]
  delete 'lists/:id', to: 'lists#destroy', as: 'delete_list'
end

app/views/shared/_card.html.erb
      <div class="card" id = "card-custom-attributes" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.1)), url('<%= list.photo.url.nil? ? "placeholder" : cl_image_path(list.photo.url, width: 400, height: 500, crop: :fill) %>')" >
        <%= link_to "", list_path(list), class: 'card-link' %>
        <div class = "card-text-bottom">
          <div class="card-avatar"></div>
          <div class="card-content">
            <div class ="card-name">
            <h3><%= list.name %></h3>
            <p id = "card-author"><%= link_to list.user.username, user_path(list.user) %></p>
            <p hidden id = "card-date"><%= list.created_at%></p>
            </div>

          <% if not list.user.photo.blank? %>
          <img src="<%=image_url list.user.photo.url%>" alt="" class="card-user">
          <% end %>

            <div class="card-likes">
              <div class="card-heart-position" id="like-container-<%= "#{list.id}"%>">
                <% if !list.favourites.nil? && current_user%>
                <% pre_like = list.favourites.find { |like| like.user_id == current_user.id} %>

                <% if pre_like %>
                <%= render 'shared/dislike', list: list, pre_like: pre_like %>
                <% else %>
                <%= render 'shared/like', list: list %>
                <% end %>

                <% else %>
                <%= render 'shared/like', list: list %>
                <% end %>
              </div>
              <div class = "like-count" id="like-count-<%= list.id %>"> <%= list.favourites.count%> </div>
            </div>
          </div>
        </div>
      </div>

app/views/shared/_dislike.html.erb
<%= link_to list_favourite_path(list, pre_like), method: :delete, id: 'dislike-button', class: 'pulse animated infinite', remote: true  do %>
  <i class="fas fa-heart pulse animated"></i>
<% end %>

app/views/shared/_dropdown-sort.html.erb
<div class="btn-group" id ="btn-group-id">
<button class="btn btn-simple" type="button" id="sort-by-label" disabled>
    Sort by:
</button>

<div class="dropdown" id="sort-by-dropdown">
  <button class="btn btn-create dropdown-toggle" id="current-sort-by" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Likes
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="#">Likes</a>
    <a class="dropdown-item" href="#">Date</a>
    <a class="dropdown-item" href="#">Author</a>
  </div>
</div>
</div>

<%= javascript_pack_tag 'plugins/dropdown' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer" <%="id=footer-list-show" if !params[:id].nil? %> >
  <div class="footer-copyright">
    © 2019 lista
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
  </div>
</div>

app/views/shared/_like.html.erb
<%= link_to list_favourites_path(list), method: :post, id: 'like-button', class: 'pulse animated', remote: true do %>
  <i class="far fa-heart pulse animated"></i>
<% end %>

app/views/shared/_likecount.html.erb
<%= @list.favourites.count %> <%= (@list.favourites.count) == 1 ? 'Like' : 'Likes' %>

app/views/shared/_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create your first list</h5>
      </div>
      <div class="modal-body">
        <%= simple_form_for(List.new) do |form| %>
        <%= form.input :name, as: :text, label: 'List name:' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn-info "><%= form.button :submit %></button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon"  <%= "id=navbar-banner-lewagon" if current_page?(root_path) || current_page?(lists_path) %> >
  <%= link_to root_path, class: "navbar-brand" do %> <span>lista</span> <% end %>

  <% if !current_page?(root_path) && !current_page?(lists_path) && current_user %>
    <div class="search-bar">
      <%= form_tag lists_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          placeholder: "Search for a place, city or country"
        %>
      <% end %>
    </div>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">


      <li class="nav-item">
        <%= link_to "Create a list", "", class: "nav-link nav-link-create-list", "data-toggle" => "modal", 'data-target' => '#exampleModal' %>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item active nav-link ml-auto">
          <%= current_user.username || current_user.email %>
        </li>

        <li class="nav-item dropdown">
          <% profile_placeholder = "https://bankwatch.org/wp-content/uploads/2018/03/Portrait_Placeholder-300x300.png" %>
          <img src="<%=image_url current_user.photo.url || profile_placeholder %>" alt="" id="navbarDropdown" data-toggle="dropdown" aria-haspopup aria-expanded="false" class="avatar dropdown-toggle">
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Profile", current_user, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>

      <% else %>
      <li class="nav-item ml-auto">
        <%= link_to "login", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

<%= render 'shared/modal' %>

app/views/shared/_share.html.erb
_share.html.erb