config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'lists#index'
  resources :users, param: :slug, only: [:show, :new, :create, :update, :edit, :destroy] do
    member do
      get :following, :followers
    end
  end
  resources :lists, only: [ :index, :show, :create, :edit, :new, :update ] do
    resources :list_places, only: [:create, :destroy]
    resources :favourites
  end

  resources :places, only: [:show, :update, :edit, :destroy]

  #resources :listplaces, only: [:new, :create, :destroy]
  resources :favourites, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :relationships, only: [:create, :destroy]
  delete 'lists/:id', to: 'lists#destroy', as: 'delete_list'
end

app/models/list_place.rb
class ListPlace < ApplicationRecord
  belongs_to :list
  belongs_to :place
  validates_presence_of :list
  validates_presence_of :place
  accepts_nested_attributes_for :place
end

app/controllers/list_places_controller.rb
class ListPlacesController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @list_place = ListPlace.new(listplace_params)
    @list_place.list = @list
    #@list_place.place = Place.new(place_params)

    @list_place.save

    respond_to do |format|
      format.html { redirect_to edit_list_path(@list) }
      format.js  # <-- will render `app/views/reviews/create.js.erb`
    end

  end

  def destroy
    @list = List.find(params[:list_id])
    @list_place = ListPlace.find(params[:id])
    @list_place.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to edit_list_path(@list)
  end

  private

  def listplace_params
    params.require(:list_place).permit(:comments, place_attributes: [:name, :address, :photo, :latitude, :longitude])
  end
end

app/views/list_places/_delete.html.erb
<%= link_to "Delete",  list_list_place_path(list, list_place),
      method: :delete,
      data: { confirm: "Are you sure?" } %>

app/views/list_places/_form.html.erb
<%= simple_form_for([ list, list_place], remote: true) do |form| %>

  <%= form.simple_fields_for :place do |j| %>
      <%= j.input :name, label: false, label_html: { class: 'form' }, :input_html => { :id => "autocomplete" }%>
      <%= j.input :address, label_html: { class: 'form' }, :input_html => { :id => "full_address" } , as: :hidden%>
      <%= j.input :latitude, label_html: { class: 'form' },  :input_html => { :id => "latitude" } , as: :hidden%>
      <%= j.input :longitude, label_html: { class: 'form' }, :input_html => { :id => "longitude" } , as: :hidden%>

  <%= form.input :comments, placeholder: 'Add a comment for this place', as: :text , label: false%>
  <%= j.input :photo, label: 'Select a nice pic:' %>
      <%= j.input :photo_cache, as: :hidden %>
<% end %>
  <div class = 'text-left'><%= form.submit 'Add new place', class: 'btn-info' %></div>

<% end %>

app/views/list_places/_show.html.erb
<div class="row" id = "place-div">
  <div class="col-lg-6">
    <h6><%=lp.place.name%></h6>
    <p><%=lp.place.address%></p>
    <p><%= '"' + lp.comments + '"'%></p>
    <p><%= render 'list_places/delete', list_place: lp, list: list%></p>
  </div>
  <div class="col-lg-6">
    <%= cl_image_tag lp.place.photo, crop: :scale, class: 'place-image' %>
    <!-- <p><%=lp.place.photo%></p> -->
  </div>
</div>

app/views/list_places/create.html.erb
<h1>Listplaces#create</h1>
<p>Find me in app/views/listplaces/create.html.erb</p>

app/views/list_places/create.js.erb
// function refreshForm(listPlaceHTML) {
//   const newListForm = document.getElementById('new_list_place');
//   console.log(newListForm);
//   console.log(listPlaceHTML);
//   newListForm.innerHTML = listPlaceHTML;
// }

function refreshForm() {

  //const inputs = document.querySelectorAll('.form-control');
  const inputs = document.getElementById('autocomplete');
  inputs.value = "";
  const inputs2 = document.getElementById('list_place_comments');
  inputs2.value = "";
  const inputs3 = document.getElementById('list_place_place_attributes_photo');
  inputs3.value = "";
}

function addListPlace(listPlaceHTML) {
  const places = document.getElementById('places');
  places.insertAdjacentHTML('beforeend', listPlaceHTML);
}

console.log(<%=@list_place.place.photo%>);

addListPlace('<%= j render "list_places/show", list: @list, lp: @list_place%>');

var photo = document.querySelector('#list_place_place_attributes_photo');

var placeholders = document.querySelectorAll(".place-image");

var placeholder = placeholders[placeholders.length - 1];

if (photo.files[0]) {
  var reader = new FileReader();
  reader.onload = (event) => {
    placeholder.src = event.target.result;
  };
  reader.readAsDataURL(photo.files[0]);
}

refreshForm();

window.scrollTo(0,document.body.scrollHeight);

// refreshForm('<%= j render "list_places/form", list: @list, list_place: ListPlace.new()%>');

// const addListenerToPhoto = () => {
//  const photo = document.querySelector('#list_place_place_attributes_photo')
//  photo.addEventListener("change", (event) => {
//    const image = event.target.files[0];
//    console.log("chnge event is triggered yoooo");
//    const placeholders = document.querySelector("place-image");
//    const placeholder = placeholders[placeholders.length - 1];
//    const reader = new FileReader();
//    reader.onload = (event) => {
//      placeholder.src = event.target.result;
//    };
//    reader.readAsDataURL(image);
//  });
// };

app/views/list_places/destroy.html.erb
<h1>Listplaces#destroy</h1>
<p>Find me in app/views/listplaces/destroy.html.erb</p>

app/views/list_places/new.html.erb
<h1>Listplaces#new</h1>
<p>Find me in app/views/listplaces/new.html.erb</p>