config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'lists#index'
  resources :users, param: :slug, only: [:show, :new, :create, :update, :edit, :destroy] do
    member do
      get :following, :followers
    end
  end
  resources :lists, only: [ :index, :show, :create, :edit, :new, :update ] do
    resources :list_places, only: [:create, :destroy]
    resources :favourites
  end

  resources :places, only: [:show, :update, :edit, :destroy]

  #resources :listplaces, only: [:new, :create, :destroy]
  resources :favourites, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :relationships, only: [:create, :destroy]
  delete 'lists/:id', to: 'lists#destroy', as: 'delete_list'
end

app/models/place.rb
class Place < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_many :list_places, dependent: :destroy, inverse_of: :place
  has_many :lists, through: :list_places

  validates :name, presence: true
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def show
  end

  def new
    @place = Place.new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  private

  def find_place
    @place = Place.find(params[:id])
    #authorize @list
  end

  def place_params
    params.require(:place).permit(:name, :address, :comment)
  end
end

app/views/places/create.html.erb
<h1>Places#create</h1>
<p>Find me in app/views/places/create.html.erb</p>

app/views/places/destroy.html.erb
<h1>Places#destroy</h1>
<p>Find me in app/views/places/destroy.html.erb</p>

app/views/places/edit.html.erb
<h1>Places#edit</h1>
<p>Find me in app/views/places/edit.html.erb</p>

app/views/places/new.html.erb
<h1>Places#new</h1>
<p>Find me in app/views/places/new.html.erb</p>

<%= simple_form_for(@place, url: list_places_path) do |f| %>
  <!-- [...] -->
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.submit 'Create list', class: 'btn btn-info'%>
  <!-- [...] -->
<% end %>

app/views/places/show.html.erb
<h1>Places#show</h1>
<p>Find me in app/views/places/show.html.erb</p>

app/views/places/update.html.erb
<h1>Places#update</h1>
<p>Find me in app/views/places/update.html.erb</p>